version: '3.7'
services:
  app:
    # Nginx conf file must have proxy as build name, app in this case
    build: app
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network
    volumes:
      - sessions:/app/flask_session/
    depends_on:
      - db
    env_file:
      - env-vars.txt
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  nginx:
    build: nginx
    restart: always
    ports:
      - 8080:8080
    networks:
      - flask_network
    env_file:
      - env-vars.txt
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env-vars.txt
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    

networks:
  flask_network:
    enable_ipv6: false

volumes:
  postgres_data:
  sessions: