name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: TFSM00/github-action-ssh-docker-compose@master
      name: Remote Deployment with Docker-Compose
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_port: ${{ secrets.SSH_PORT }}
        docker_compose_prefix: microtasker