name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
      name: Remote Deployment with Docker-Compose
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: docker-deploy
        ssh_port: ${{ secrets.SSH_PORT}}
        docker_compose_prefix: microtasker
        pull: true # Update images when pulling